-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 02, 2024 at 10:34 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `projekt`
--
CREATE DATABASE IF NOT EXISTS `projekt` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_croatian_ci;
USE `projekt`;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `name` varchar(32) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `surname` varchar(64) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `username` varchar(32) NOT NULL,
  `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `permission` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_croatian_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `surname`, `username`, `password`, `permission`) VALUES
(4, 'Marko', 'Gradiščaj', 'mgradiscaj', '$2y$10$AaZQSkrVLi7K3W4tvxqyJuqqECdZ6pJZ6sue3CIgn.MJFi2fMjnmO', 1),
(5, 'Đuro', 'Đurić', 'duroDuric', '$2y$10$5HBx3b80/uC3L/ry9qwwUOK8aNuA39yFOUoGfZplEIGq3UzyLQYTC', 0),
(13, 'Mirko', 'Mirkic', 'mirkoMirkic', '$2y$10$k/wQyAQbBJfXQrLhNb8sEeF8FSRivi99aRrR1oi4igucmlUNSq0U6', 0);

-- --------------------------------------------------------

--
-- Table structure for table `vijesti`
--

CREATE TABLE `vijesti` (
  `id` int(11) NOT NULL,
  `datum` varchar(32) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `naslov` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `sazetak` text CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `tekst` text CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `slika` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `kategorija` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `arhiva` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_croatian_ci;

--
-- Dumping data for table `vijesti`
--

INSERT INTO `vijesti` (`id`, `datum`, `naslov`, `sazetak`, `tekst`, `slika`, `kategorija`, `arhiva`) VALUES
(1, '16.05.2024', 'Novi Rekreativni DJI dron', 'DJI je upravo predstavio svoj najnoviji model rekreativnog drona, Mavic 2 Pro', 'DJI, vodeći svjetski proizvođač dronova, nedavno je lansirao svoj najnoviji model iz Mavic serije - Mavic 2 Pro. Ovaj dron, dizajniran za rekreativne korisnike, donosi niz unapređenja i novih značajki koje ga čine jednim od najnaprednijih dronova na tržištu.\r\n\r\nJedna od ključnih karakteristika Mavic 2 Pro drona je njegova vrhunska kamera. Opremljen Hasselblad L1D-20c kamerom s 1-inčnim CMOS senzorom, ovaj dron omogućava snimanje fotografija u rezoluciji od 20 megapiksela te videozapisa u 4K kvaliteti. Kamera također nudi prilagodljivi otvor blende od f/2.8 do f/11, što korisnicima omogućava izvrsnu kontrolu nad ekspozicijom i dubinom polja, bez obzira na uvjete osvjetljenja.\r\n\r\nMavic 2 Pro dolazi s unaprijeđenim sustavom za izbjegavanje prepreka, koji koristi 10 senzora smještenih na različitim dijelovima drona kako bi osigurao sigurnost tijekom leta. Ova tehnologija omogućava dronu da automatski prepozna i zaobiđe prepreke, čime se smanjuje rizik od nesreća i omogućava korisnicima da se usredotoče na snimanje.\r\n\r\nNovi dron također se može pohvaliti impresivnim vremenom leta od 31 minute i maksimalnom brzinom od 72 km/h, što ga čini izuzetno agilnim i pouzdanim u različitim uvjetima. Dodatne značajke poput ActiveTrack 2.0, Hyperlapse i Panorama modova omogućavaju korisnicima stvaranje dinamičnih i kreativnih sadržaja s lakoćom.\r\n\r\nDJI je također unaprijedio kontroler Mavic 2 Pro drona, pružajući korisnicima još intuitivnije i jednostavnije upravljanje. Nova tehnologija prijenosa OcuSync 2.0 omogućava prijenos uživo u 1080p rezoluciji na udaljenosti do 8 kilometara, što je značajno poboljšanje u odnosu na prethodne modele.\r\n\r\nCijena Mavic 2 Pro drona prilagođena je entuzijastima koji traže najbolju moguću kvalitetu po pristupačnoj cijeni. DJI nudi različite pakete s dodatnom opremom, uključujući dodatne baterije, torbe za nošenje i filtre za kameru, čime korisnici mogu prilagoditi svoje iskustvo prema vlastitim potrebama.\r\n\r\nLansiranje Mavic 2 Pro drona pokazuje DJI-evu posvećenost inovacijama i kontinuiranom unapređenju svojih proizvoda. Ovaj dron sigurno će postati omiljen među rekreativnim korisnicima koji traže vrhunsku kvalitetu, performanse i pouzdanost.', 'm2.jpg', 'Rekreativni dronovi', 1),
(2, '16.05.2024', 'DJI Phantom 5: Nova Era Komercijalnih Dronova', 'DJI je najavio lansiranje svog najnovijeg komercijalnog drona. Ovaj dron obećava napredne funkcije, uključujući izmjenjive kamere, poboljšane letne performanse i napredne senzore. ', 'Nakon višemjesečnih špekulacija i iščekivanja, DJI je konačno otkrio svoj najnoviji dodatak Phantom seriji - DJI Phantom 5. Ovaj dron donosi niz impresivnih poboljšanja koja će revolucionirati komercijalnu upotrebu dronova.\r\n\r\nJedna od najistaknutijih značajki DJI Phantom 5 je mogućnost izmjenjivih kamera. Korisnici sada mogu birati između različitih objektiva ovisno o specifičnim potrebama snimanja, što je idealno za profesionalne fotografe i videografe koji zahtijevaju visoku kvalitetu i fleksibilnost. Phantom 5 dolazi s najnovijom tehnologijom senzora, pružajući nevjerojatno detaljne i oštre snimke čak i u zahtjevnim uvjetima osvjetljenja.\r\n\r\nUz vrhunsku kameru, Phantom 5 nudi poboljšane letne performanse. Novi motori i napredni kontrolni sustavi omogućuju stabilniji let, veći domet i duže vrijeme leta. Ovaj dron je također opremljen naprednim sustavima izbjegavanja prepreka, što značajno smanjuje rizik od nesreća i omogućuje sigurnije operacije, posebno u složenim okruženjima.\r\n\r\nDJI Phantom 5 također je dizajniran s mislima na profesionalce u raznim industrijama. Njegove napredne mogućnosti čine ga idealnim za preciznu poljoprivredu, inspekcije infrastrukture, kartografiju i mnogo više. Kombinacija dugotrajnog baterijskog vijeka, robusne izrade i naprednih senzora čini ga nezamjenjivim alatom za profesionalce koji zahtijevaju pouzdanost i visokih performansi.\r\n\r\nSlužbeni datum izlaska i cijena DJI Phantom 5 još nisu potvrđeni, no očekuje se da će biti dostupan na tržištu krajem ove godine. S obzirom na dosadašnju reputaciju DJI-ja za inovacije i kvalitetu, Phantom 5 će zasigurno postati lider u komercijalnoj upotrebi dronova. Profesionalci diljem svijeta s nestrpljenjem iščekuju priliku da testiraju ovaj impresivni novi uređaj i iskoriste njegove napredne mogućnosti u svojim projektima.\r\n\r\nDJI Phantom 5 nije samo još jedan dron; on je korak naprijed u tehnologiji koja omogućuje nove načine rada i kreativne izražaje, potvrđujući DJI-jevu vodeću poziciju na tržištu dronova.', 'p4.jpg', 'Komercijalni dronovi', 0),
(3, '16.05.2024', 'Popust na Moderne Komercijalne Dronove', 'Uhvatite super popuste na komercijalne dronove', 'Najbolji Popusti na komercijalne dronove samo u Aviteh dućanu u Zagrebu.\r\n\r\nTražite li vrhunske dronove po fantastičnim cijenama? Ne tražite dalje! Aviteh  nudi najveće popuste na najnovije modele dronova visoke kvalitete.\r\n\r\nNevjerojatne Cijene, Još Bolji Dronovi\r\n\r\nNaša ponuda obuhvaća širok spektar najnovijih dronova po sniženim cijenama! Bez obzira želite li profesionalni dron za fotografske projekte ili zabavni dron za letenje iznad parkova, imamo savršeno rješenje za vas.\r\n\r\nNapredne Značajke za Nezaboravna Iskustva\r\n\r\nNaši dronovi opremljeni su naprednim značajkama koje pružaju nevjerojatno iskustvo letenja. Uživajte u visokokvalitetnim kamerama, dugom vijeku baterije i intuitivnom upravljanju, sve po nevjerojatnoj cijeni.\r\n\r\nJednostavna Kupovina Online\r\n\r\nKupovina dronova nikada nije bila jednostavnija! Posjetite našu web trgovinu na AviTech.hr i pregledajte našu široku ponudu. Odaberite svoj omiljeni model, dodajte ga u košaricu i uživajte u brzoj dostavi na vaša vrata.\r\n\r\nIskoristite Ove Ponude Dok Traju!\r\n\r\nOvo je prilika koju ne želite propustiti! Posjetite nas danas na Aviteh i iskoristite najbolje popuste na dronove. Brzo, jednostavno i povoljno!\r\n\r\nNe propustite priliku za vlastiti dron po fantastičnoj cijeni! Aviteh je vaša destinacija za najbolje ponude na tržištu dronova!', 'popusti.jpg', 'Komercijalni dronovi', 0),
(14, '16.05.2024', 'Novi kompaktni rekreacijski dron', 'DJI lansirao najnoviji rekreacijski dron, Mini 4 Pro, koji obećava revolucionirati način letenja', 'DJI Mini 4 Pro. Ovaj kompaktni, ali moćni dron obećava revolucionirati način na koji doživljavamo letenje.\r\n\r\nUltra-kompaktni dizajn: DJI Mini 4 Pro dolazi s ultra-kompaktnim dizajnom koji ga čini jednim od najmanjih dronova na tržištu. Unatoč svojoj veličini, ovaj dron je opremljen visokokvalitetnom kamerom i nizom naprednih značajki koje ga čine idealnim izborom za rekreacijske ljubitelje.\r\n\r\nNapredne značajke leta: Jedna od ključnih prednosti DJI Mini 4 Pro je niz naprednih značajki leta koje omogućuju jednostavno upravljanje čak i početnicima. Uključuje inteligentne načine leta poput \"Point of Interest\" i \"Follow Me\", što omogućuje impresivne letačke performanse s minimalnim naporom.\r\n\r\nVisokokvalitetna kamera: Iako je DJI Mini 4 Pro kompaktan, nudi visokokvalitetnu kameru koja snima u 4K rezoluciji. Ova kamera omogućuje snimanje izvanrednih zračnih fotografija i videa, čime se osigurava da svaki trenutak bude zabilježen s nevjerojatnom jasnoćom i detaljima.\r\n\r\nDulje vrijeme letenja: Jedan od glavnih izazova s kojima se susreću vlasnici dronova je ograničenje vremena letenja. Međutim, DJI Mini 4 Pro rješava taj problem s impresivnim vremenom letenja od preko 30 minuta, što omogućuje dulje i ugodnije iskustvo letenja bez potrebe za čestim punjenjem baterije.', 'mini4Pro.jpg', 'Rekreativni dronovi', 0),
(15, '16.05.2024', 'Tvrtka DJI dobila novog CEO-a', 'Tvrtka DJI, globalni lider u industriji dronova, nedavno je objavila imenovanje novog CEO-a\r\n', 'Tvrtka DJI, vodeći svjetski proizvođač dronova, nedavno je objavila imenovanje novog CEO-a. Wu Gongfu, dugogodišnji veteran tehnološke industrije, preuzima vođenje kompanije s ciljem nastavka inovacija i rasta.\r\n\r\nGospodin Gongfu donosi sa sobom bogato iskustvo i stručnost u vođenju tehnoloških tvrtki. Njegovo imenovanje dolazi u ključnom trenutku za DJI, koji se suočava s izazovima sve veće konkurencije i potražnje za naprednim rješenjima u području bespilotnih letjelica.\r\n\r\nNjegova vizija za budućnost DJI-a uključuje kontinuirani razvoj novih tehnologija, poboljšanje postojećih proizvoda te proširenje poslovanja u nove vertikale. Gospodin Gongfu predstavlja snažno vodstvo koje će nastojati održati DJI na vrhu industrije dronova.', 'CEOdji.jpg', 'Ostalo', 0),
(16, '17.05.2024', 'Otvorena Nova Moderna Dron Tvrtka ', 'Tvrtka nudi najnovije modele dronova za rekreativnu i profesionalnu upotrebu, uz vrhunsku korisničku podršku i povoljne cijene.', 'Na tržištu dronova pojavila se nova zvijezda ? tvrtka \"SkyFly Drones\", koja je nedavno otvorila svoja vrata. Smještena u srcu tehnološkog parka u Zagrebu, \"SkyFly Drones\" nudi širok asortiman najnovijih modela dronova, prilagođenih kako rekreativnim korisnicima tako i profesionalcima.\r\n\r\nOsnivač i CEO tvrtke, Marko Jurić, istaknuo je kako je cilj \"SkyFly Drones\" pružiti vrhunsku tehnologiju po pristupačnim cijenama, uz izvrsnu korisničku podršku. \"Vjerujemo da dronovi imaju nevjerojatan potencijal u raznim industrijama, od fotografije i videografije do poljoprivrede i sigurnosti. Naša misija je omogućiti svima da iskoriste tu tehnologiju na najbolji mogući način,\" rekao je Jurić.\r\n\r\nU ponudi \"SkyFly Drones\" nalaze se dronovi renomiranih marki, kao i vlastiti brendovi koji su prošli rigorozna testiranja kvalitete i performansi. Tvrtka nudi i dodatnu opremu, rezervne dijelove, te servis i podršku kako bi kupci imali potpuno zadovoljstvo svojim dronovima.\r\n\r\nOsim prodaje dronova, \"SkyFly Drones\" planira organizirati radionice i tečajeve za sve razine korisnika, od početnika do profesionalaca. Također, u planu je i uspostava programa najma dronova za one koji žele isprobati različite modele prije kupnje.\r\n\r\nOtvorenje \"SkyFly Drones\" predstavlja značajan korak naprijed u dostupnosti napredne dron tehnologije za širu javnost. S inovativnim pristupom i posvećenošću kvaliteti, \"SkyFly Drones\" je spreman postati vodeći igrač na tržištu dronova.', 'skyflyTvrtka.jpeg', 'Ostalo', 0),
(23, '17.05.2024', 'Veliki Popusti na Rekreativne Dronove', 'Iskoristite nevjerojatne popuste na najnovije rekreativne dronove i osigurajte svoj primjerak po sniženoj cijeni.', 'Najbolji Popusti na Rekreativne Dronove samo u Links Dućanu!\r\nTražite li vrhunske rekreativne dronove po povoljnim cijenama? Potražite najbolje ponude u Links dućanu! Sada možete nabaviti najnovije modele dronova po sniženim cijenama i uživati u nevjerojatnim pogodnostima.\r\n\r\nNeodoljive Cijene i Izvrsni Dronovi\r\nLinks dućan nudi raznolike rekreativne dronove po pristupačnim cijenama! Bez obzira jeste li početnik ili iskusni pilot, pronaći ćete savršeni dron za svoje potrebe. Njihova ponuda uključuje modele s različitim značajkama, idealne za sve razine iskustva.\r\n\r\nNapredne Tehnologije za Najbolje Iskustvo\r\nNjihovi dronovi dolaze s naprednim tehnologijama koje osiguravaju izvanredno iskustvo letenja. Uživajte u visokoj kvaliteti kamera, dugotrajnoj bateriji i jednostavnom upravljanju, sve po povoljnoj cijeni.\r\n\r\nJednostavna Kupovina Online\r\nKupnja dronova nikada nije bila jednostavnija! Posjetite njihovu web stranicu na Links.hr, pregledajte široku ponudu i odaberite svoj omiljeni model. Dodajte ga u košaricu i uživajte u brzoj dostavi iz udobnosti svog doma.\r\n\r\nIskoristite Ponudu Dok Traje!\r\nOvo je prilika koju ne smijete propustiti! Posjetite Links dućan danas i iskoristite fantastične popuste na dronove. Brzo, jednostavno i povoljno', 'popustiLinks.jpg', 'Rekreativni dronovi', 0),
(24, '17.05.2024', 'Popularna Tvrtka IziDrones Promijenila Ime u WeLoveDrones', 'Tvrtka IziDrones, poznata po svojim inovativnim rješenjima u svijetu dronova, službeno je promijenila ime.', 'Tvrtka IziDrones, koja je postala sinonim za kvalitetne i inovativne dronove, najavila je značajnu promjenu u svom poslovanju. Od danas, tvrtka će poslovati pod novim imenom ? WeLoveDrones. Ova promjena imena dolazi kao dio strateškog rebrendiranja koje ima za cilj bolje povezivanje s korisnicima i širenje ponude proizvoda i usluga.\r\n\r\nRazlozi za Promjenu Imena\r\nPrema riječima izvršnog direktora tvrtke, Marka Horvata, promjena imena odražava novu viziju i misiju tvrtke. \"Željeli smo ime koje bolje izražava našu strast prema dronovima i našu predanost korisnicima. WeLoveDrones savršeno oslikava naš entuzijazam i posvećenost ovoj tehnologiji,\" izjavio je Horvat.\r\n\r\nŠto Ovo Znači za Kupce?\r\nKupci mogu očekivati kontinuitet u kvaliteti i inovativnosti proizvoda, uz dodatne pogodnosti. WeLoveDrones planira proširiti svoju ponudu kako bi uključila nove modele dronova, dodatnu opremu, te napredne usluge poput dron edukacije i servisa. Promjena imena također donosi novo vizualno iskustvo kroz osvježenje brenda, uključujući novi logotip i redizajniranu web stranicu.\r\n\r\nNovi Projekti i Partnerstva\r\nWeLoveDrones će nastaviti razvijati i lansirati napredne tehnologije u području dronova, uključujući projekte u suradnji s tehnološkim partnerima i istraživačkim institucijama. Cilj je pružiti korisnicima najnovija rješenja koja mogu unaprijediti različite industrije, od poljoprivrede do sigurnosnih službi.', 'tvrtkaIme.jpeg', 'Ostalo', 1),
(25, '17.05.2024', 'Najprodavaniji Rekreativni Dron 2023. godine', 'Ovaj model je osvojio srca mnogih entuzijasta i postao omiljeni izbor za snimanje zapanjujućih zračnih fotografija i videozapisa.', 'U svijetu dronova, 2023. godina je donijela mnogo uzbuđenja, a jedan model se posebno istaknuo među rekreativnim korisnicima ? DJI Air 3. Ovaj dron je osvojio tržište svojom kombinacijom vrhunskih značajki, pristupačne cijene i jednostavnog korištenja, čineći ga jednim od najprodavanijih dronova ove godine.\r\n\r\nZnačajke koje Osvajaju\r\nDJI Air 3 dolazi s impresivnim skupom značajki koje ga čine izvanrednim izborom za rekreativne pilote. Opremljen 4K kamerom visoke rezolucije, ovaj dron omogućava snimanje kristalno čistih fotografija i videozapisa. Stabilizacija slike putem gimbala osigurava glatke i profesionalne snimke, čak i pri vjetrovitim uvjetima.\r\n\r\nJedna od ključnih prednosti DJI Air 3 je njegov kompaktan dizajn i lakoća nošenja. Teži manje od 600 grama, što ga čini iznimno prenosivim i jednostavnim za upotrebu u različitim situacijama. Uz to, njegov napredni sustav za izbjegavanje prepreka omogućava sigurnije letenje, što je posebno važno za početnike.\r\n\r\nIzvrsne Performanse\r\nS maksimalnim vremenom leta od 34 minute, DJI Air 3 pruža dovoljno vremena za hvatanje savršenih kadrova. Njegov domet letenja od 10 kilometara omogućava korisnicima istraživanje i snimanje velikih površina bez gubitka signala. Dron također podržava različite načine letenja, uključujući Follow Me, Point of Interest i Waypoints, čime se povećava kreativna sloboda pilota.\r\n\r\nPopularnost i Prodajni Uspjeh\r\nPopularnost DJI Air 3 može se pripisati njegovom izvanrednom omjeru cijene i kvalitete. Mnogi korisnici hvale ovaj model zbog njegove pouzdanosti i performansi, a pozitivne recenzije doprinijele su njegovom uspjehu na tržištu. Prema podacima iz industrije, DJI Air 3 je jedan od najprodavanijih dronova 2023. godine, posebno među rekreativnim korisnicima koji žele visokokvalitetni dron po razumnoj cijeni.', 'air3.jpg', 'Rekreativni dronovi', 0),
(26, '18.05.2024', 'Najuspješnija Tvrtka Dronova Današnjice', 'Moderna Tvrtka dronova postala je globalni lider u industriji dronova, zahvaljujući inovacijama, vrhunskoj tehnologiji i širokoj paleti proizvoda koji zadovoljavaju potrebe profesionalaca i hobista', 'Tvrtka se istaknula zahvaljujući svojoj sposobnosti da kontinuirano uvodi tehnološke inovacije koje postavljaju nove standarde u industriji. DJI-jev Mavic serija, Phantom modeli i najnoviji Inspire dronovi donijeli su revoluciju u zračno snimanje, omogućujući profesionalcima i hobistima da s lakoćom snimaju zapanjujuće fotografije i videozapise.\r\n\r\nOsim impresivne tehnologije, DJI se također ponosi širokom paletom proizvoda koji uključuju dronove za različite svrhe - od rekreativnih dronova za entuzijaste do naprednih modela namijenjenih komercijalnoj upotrebi kao što su inspekcije, kartografija i poljoprivreda. Tvrtka je također značajno uložila u razvoj sigurnosnih sustava, osiguravajući da su njihovi dronovi sigurni za upotrebu i u urbanim sredinama.\r\n\r\nJedan od ključnih faktora uspjeha DJI-a je njihova posvećenost korisničkom iskustvu. Redovito izdaju ažuriranja softvera koja poboljšavaju performanse dronova i dodaju nove funkcionalnosti, čime zadržavaju korisnike zadovoljnima i lojalnima. Osim toga, DJI-jev tim za korisničku podršku pruža izvanrednu podršku, brzo rješavajući bilo kakve tehničke probleme s kojima se korisnici mogu suočiti.\r\n\r\nGledajući u budućnost, DJI planira nastaviti širiti svoje inovacije na nova područja, uključujući razvoj autonomnih sustava i umjetne inteligencije koja će dodatno poboljšati sposobnosti njihovih dronova. S obzirom na dosadašnje uspjehe, nema sumnje da će DJI nastaviti dominirati industrijom dronova, postavljajući nove standarde i inspirirajući sljedeću generaciju tehnologije zračnog snimanja.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 'logo2.jpg', 'Ostalo', 0),
(27, '18.05.2024', 'Najprodavaniji Komercijalni Dron 2023. Godine', 'Pogledajte koji je jedan od najprodavanijih dronova 2023. godine', 'Jedan od glavnih razloga za popularnost Mavic 3 modela je njegova vrhunska kamera, koja dolazi s Hasselblad tehnologijom. Kamera omogućava snimanje u 5.1K rezoluciji, pružajući izuzetnu jasnoću i detalje, što ga čini savršenim izborom za profesionalne fotografe i videografe. Osim toga, Mavic 3 nudi napredne funkcije poput automatskog izbjegavanja prepreka, koje omogućavaju sigurnije i preciznije letenje čak i u izazovnim uvjetima.\r\n\r\nTrajanje baterije također je značajno unaprijeđeno u Mavic 3 modelu. S mogućnošću letenja do 46 minuta s jednim punjenjem, korisnici mogu pokriti veće površine i provoditi dulje snimanja bez potrebe za čestim prekidima. Ovo je posebno korisno za industrije kao što su poljoprivreda, građevina i inspekcije, gdje je efikasnost ključna.\r\n\r\nMavic 3 također dolazi s poboljšanim sustavom za prijenos slike, koji omogućava stabilan i jasan prijenos uživo do 15 kilometara udaljenosti. Ova značajka omogućava operaterima da dobiju stvarno vrijeme pregledavanja iz zraka, što je od velike važnosti za nadzor i inspekcije.\r\n\r\nJednostavnost korištenja je još jedan aspekt koji je pridonio popularnosti Mavic 3. Intuitivna aplikacija i jednostavne kontrole omogućavaju i početnicima i iskusnim profesionalcima da maksimalno iskoriste mogućnosti drona. Automatski načini letenja, poput ActiveTrack i MasterShots, dodatno olakšavaju snimanje profesionalnog izgleda bez potrebe za složenim postavkama.', 'mavic3.jpg', 'Komercijalni dronovi', 0),
(28, '20.05.2024', 'Novi Rekreativni Prijenosni Dron koji Oduzima Dah', 'Novi rekreativni dron oduševljava ljubitelje tehnologije i entuzijaste svojom naprednom funkcionalnošću i pristupačnom cijenom, čineći letenje dostupnim svima.', 'Najnoviji član obitelji DJI dronova, DJI Mini 5, predstavlja revolucionarni korak naprijed u svijetu bespilotnih letjelica. Ovaj prijenosni dron kombinira kompaktni dizajn s visokokvalitetnom kamerom i naprednim značajkama letenja, pružajući korisnicima nevjerojatno iskustvo letenja iz zraka.\n\nJedna od najznačajnijih karakteristika DJI Mini 5 je njegova mala veličina i lakoća. Ovaj dron može stati u dlan vaše ruke i teži manje od 250 grama, što ga čini jednim od najprijenosnijih dronova na tržištu. Bez obzira jeste li na putu ili u prirodi, DJI Mini 5 je uvijek spreman za letenje.\n\nUnatoč svojoj maloj veličini, DJI Mini 5 opremljen je visokokvalitetnom kamerom koja omogućuje snimanje impresivnih fotografija i videozapisa u 4K rezoluciji. Kamera koristi 3-osnu stabilizaciju slike kako bi osigurala glatke i stabilne snimke čak i pri brzom letenju ili u vjetrovitim uvjetima.\n\nPametni letni sustav DJI Mini 5 omogućuje jednostavno upravljanje dronom, čak i za početnike. Napredne značajke kao što su automatsko slijetanje i povratak kući čine letenje sigurnim i jednostavnim, dok se inteligentni modovi letenja poput Point of Interest i Waypoint omogućuju korisnicima da snime spektakularne prizore s lakoćom.\n\nDJI Mini 5 također dolazi s nizom dodatnih značajki koje poboljšavaju korisničko iskustvo. Pametni sustav baterije omogućuje dulje vrijeme letenja, dok aplikacija DJI Fly pruža korisne alate za uređivanje i dijeljenje snimaka iz zraka.', 'm5.jpg', 'Rekreativni dronovi', 1),
(34, '23.05.2024', 'Novi Kompaktni Rekreacijski Dron', 'Prema najnovijim informacijama, DJI planira lansirati svoj najnoviji model komercijalnog drona.', 'DJI, vodeći svjetski proizvođač dronova, ponovno pomiče granice tehnologije sa svojim najnovijim proizvodom - Inspire 4 dronom. Ovaj novi model, koji se očekuje na tržištu krajem ove godine, obećava donijeti značajna poboljšanja u performansama, kvaliteti snimanja i autonomiji leta, čime će postaviti nove standarde u komercijalnoj upotrebi dronova.\r\n\r\nInspire 4 donosi inovacije koje će zadovoljiti potrebe profesionalnih fotografa, videografa i drugih komercijalnih korisnika. Glavne značajke uključuju:\r\n\r\nNapredna kamera: Novi senzor visokog razlučivanja omogućuje snimanje videozapisa u 8K rezoluciji, uz poboljšanu stabilizaciju slike i dinamički raspon.\r\nPovećana autonomija leta: Sa znatno duljim vremenom leta, Inspire 4 omogućava produžene operacije bez potrebe za čestim punjenjem baterija.\r\nPoboljšana preciznost: Zahvaljujući novim tehnologijama pozicioniranja i naprednim senzorima, ovaj dron osigurava izuzetnu preciznost i stabilnost u letu.\r\nSigurnosne značajke: Inspire 4 dolazi s nizom sigurnosnih funkcija, uključujući automatsko izbjegavanje prepreka i napredne sustave za povratak kući.\r\nModularni dizajn: Omogućuje jednostavnu zamjenu dijelova i nadogradnju sustava, što ga čini idealnim izborom za dugoročnu upotrebu u različitim industrijama.\r\n\"Oduševljeni smo što možemo predstaviti Inspire 4, koji će zasigurno revolucionirati način na koji se dronovi koriste u komercijalne svrhe,\" rekao je glasnogovornik DJI-a. \"Naš cilj je omogućiti korisnicima da postignu još veću kreativnost i učinkovitost u svom radu, uz najvišu razinu sigurnosti i pouzdanosti.\"\r\n\r\nIako službeni datum lansiranja još nije objavljen, izvori bliski kompaniji navode da će Inspire 4 biti dostupan za prednarudžbu krajem ljeta, s isporukom planiranom za jesen. S obzirom na povijest uspješnih proizvoda ove tvrtke, očekuje se veliki interes i potražnja za ovim naprednim dronom.', 'noviKomercDron.jpg', 'Komercijalni dronovi', 0),
(35, '23.05.2024', 'Novi Rekreativni DJI Dron', 'Otkriveni Detalji o Nadolazećem Rekreativnom DJI Dronu', 'Nakon više mjeseci špekulacija i nagađanja, kineski proizvođač dronova DJI sprema se iznenaditi svijet s lansiranjem svog najnovijeg rekreativnog drona - DJI Mavic Air 4. Iako službeni detalji još nisu objavljeni, procurjeli izvori otkrivaju da će ovaj dron postaviti nove standarde u zračnoj fotografiji i videografiji.\r\n\r\nPrema onome što se dosad saznalo, DJI Mavic Air 4 će imati niz poboljšanja u odnosu na svoje prethodnike. Očekuje se da će imati napredne značajke leta koje će olakšati upravljanje i pružiti korisnicima još veću kontrolu nad letom. Također, glavni fokus će biti na kvaliteti kamere i stabilizaciji, s visokom razlučivošću snimaka i iznimnom stabilnošću čak i u zahtjevnim uvjetima.\r\n\r\nNavodi o nadolazećem DJI Mavic Air 4 već su izazvali uzbuđenje među entuzijastima i profesionalcima zračne fotografije širom svijeta. Mnogi se nadaju da će ovaj dron ponuditi inovativne značajke koje će im omogućiti da dosegnu nove visine u svom radu.\r\n\r\nUnatoč očekivanjima, službeni datum izlaska i cijena još uvijek nisu potvrđeni. Međutim, s obzirom na povijest DJI-ja i njihovu reputaciju za izvrsnost, očekuje se da će DJI Mavic Air 4 biti dostupan po konkurentnoj cijeni i da će privući široku pažnju kupaca. S nestrpljenjem se očekuje službeno objavljivanje detalja o ovom izvanrednom dronu koji će zasigurno promijeniti način na koji gledamo na zračnu fotografiju i videografiju.', 'ma4.jpg', 'Rekreativni dronovi', 0),
(42, '27.05.2024', 'Važnost Komercijalnih Dronova', 'Korisnost komercijalnih dronova danas - igraju veliku ulogu u različitim poslovima', 'Komercijalni dronovi su postali neizostavni alat u današnjem svijetu, omogućujući inovativne perspektive i efikasnost u različitim sektorima. Njihova sposobnost da lebde u zraku i pruže visokokvalitetne snimke i podatke otvara nove mogućnosti i promjenjuje način na koji obavljamo različite zadatke i poslove.\r\n\r\nJedno od područja gdje su komercijalni dronovi ostvarili značajan utjecaj je filmska industrija. Umjesto skupih helikopterskih snimanja, sada se mogu koristiti dronovi kako bi se uhvatili impresivni kadrovi iz zraka, pružajući filmašima potpuno novu dimenziju za izražavanje svoje kreativnosti.\r\n\r\nOsim toga, građevinski sektor također je doživio revoluciju zahvaljujući komercijalnim dronovima. Brze i precizne inspekcije gradilišta omogućuju arhitektima i inženjerima da dobiju detaljne informacije o napretku projekta i identificiraju potencijalne probleme ili sigurnosne prijetnje.\r\n\r\nU poljoprivredi, komercijalni dronovi pružaju mogućnost snimanja multispektralnih slika koje pomažu poljoprivrednicima da prate stanje usjeva, identificirajući područja koja zahtijevaju dodatnu njegu ili tretman, i optimizirajući upotrebu resursa poput vode i gnojiva.\r\n\r\nNadzor infrastrukture također je područje gdje su komercijalni dronovi postali neizostavni. Redoviti pregledi cjevovoda, električnih mreža i telekomunikacijskih stupova iz zraka omogućuju otkrivanje oštećenja ili kvarova prije nego što dođe do ozbiljnih problema, što pomaže u održavanju pouzdanosti i sigurnosti infrastrukture.', 'commercialDrones.jpeg', 'Komercijalni dronovi', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`);

--
-- Indexes for table `vijesti`
--
ALTER TABLE `vijesti`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- AUTO_INCREMENT for table `vijesti`
--
ALTER TABLE `vijesti`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=81;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
